# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x08taskflow\"*\n\x0bTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\";\n\x0cTaskResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"$\n\x10HeartbeatRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\"4\n\x11HeartbeatResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\x93\x01\n\rWorkerService\x12<\n\x0b\x45xecuteTask\x12\x15.taskflow.TaskRequest\x1a\x16.taskflow.TaskResponse\x12\x44\n\tHeartbeat\x12\x1a.taskflow.HeartbeatRequest\x1a\x1b.taskflow.HeartbeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=24
  _globals['_TASKREQUEST']._serialized_end=66
  _globals['_TASKRESPONSE']._serialized_start=68
  _globals['_TASKRESPONSE']._serialized_end=127
  _globals['_HEARTBEATREQUEST']._serialized_start=129
  _globals['_HEARTBEATREQUEST']._serialized_end=165
  _globals['_HEARTBEATRESPONSE']._serialized_start=167
  _globals['_HEARTBEATRESPONSE']._serialized_end=219
  _globals['_WORKERSERVICE']._serialized_start=222
  _globals['_WORKERSERVICE']._serialized_end=369
# @@protoc_insertion_point(module_scope)
